Adjusted expected output for a couple of the Replace tests for a greedy RewriteExpr.
Some Replace tests still don't pass using Rewrite.

All tests doing insertions using OptionalRewrite don't produce any non-empty
outputs; these include tests 23e - 23i.

Also, test 25c fails with an unexpected exception:
  Error: Unhandled forward: prev = O_$o(O_$i(Col($o:X))), next = O_$o(O_$i(Col($o:X)))
This test (25c) has the priority set as ($o, $i), which is reversed from test 25a
(default: $i, $o) and test 25b (set: $i, $o), both of which pass.